# Single Cell analysis bat dragon

In [1]:
from itertools import product
from pathlib import Path

import pandas as pd
import numpy as np

In [30]:
# Trying things on the bat_dragon_DE file from the drive

# animal = 'bat'
animal = 'komodo'

# sample_type = 'lps'
sample_type = 'pic'


base_filepath = f'../../data/single_cell/animals/{animal}/{sample_type}/{animal}_{sample_type}.csv'
print(base_filepath)

../../data/single_cell/animals/komodo/pic/komodo_pic.csv

In [31]:
df_komodo_pic = pd.read_csv(base_filepath, index_col=0)
df_komodo_pic.sort_index()

df_komodo_pic

,pic_logfoldchanges,pic_pvals,pic_pvals_adj,pic_pts,UNST_pts,1to1_bat_dragon
pic_names,,,,,,
FTH1_1,2.582310,0.000000e+00,0.000000e+00,0.988493,0.923642,no
IRF1,3.701248,1.128600e-217,1.059300e-213,0.711738,0.185512,no
TNIP1,2.522758,1.101900e-208,6.894900e-205,0.780783,0.368086,TNIP1
HELZ2_1,2.542794,1.258000e-205,5.903900e-202,0.845224,0.475281,no
TNF,3.223141,7.287700e-164,2.736100e-160,0.681243,0.215859,TNF
...,...,...,...,...,...,...
SLC7A11,-0.662322,1.643360e-28,1.421620e-26,0.780207,0.820362,SLC7A11
VIM_1,-0.419322,2.615560e-29,2.345590e-27,0.964327,0.964758,no
RPS18,-0.285248,1.054870e-29,9.659490e-28,0.979287,0.977484,no
CTSZ_2,-0.672606,4.302460e-34,4.954960e-32,0.732451,0.759667,no
POR,-0.874197,8.829730e-52,1.801650e-49,0.722094,0.767499,POR

#### Filtering out rows that are not 1 to 1 ortholgs (has 'no' in the 1to1_bat_dragon column)

In [32]:
# Filter out the row where 'no' appears

filtered_df_komodo_pic = df_komodo_pic[df_komodo_pic['1to1_bat_dragon'] != 'no']
filtered_df_komodo_pic

,pic_logfoldchanges,pic_pvals,pic_pvals_adj,pic_pts,UNST_pts,1to1_bat_dragon
pic_names,,,,,,
TNIP1,2.522758,1.101900e-208,6.894900e-205,0.780783,0.368086,TNIP1
TNF,3.223141,7.287700e-164,2.736100e-160,0.681243,0.215859,TNF
RNF213,2.893878,4.006000e-162,1.253300e-158,0.677215,0.285365,RNF213
STK17A,2.435132,7.546700e-151,1.574100e-147,0.678941,0.255507,STK17A
UNC13D,1.741788,1.349100e-127,2.110400e-124,0.795742,0.441508,UNC13D
...,...,...,...,...,...,...
MERTK,-0.843813,3.519710e-22,2.145190e-20,0.472957,0.582966,MERTK
SMAP2,-0.524367,1.233610e-23,8.068750e-22,0.734753,0.738130,SMAP2
TAF10,-0.256755,2.403090e-27,1.969910e-25,0.911392,0.864415,TAF10
SLC7A11,-0.662322,1.643360e-28,1.421620e-26,0.780207,0.820362,SLC7A11
POR,-0.874197,8.829730e-52,1.801650e-49,0.722094,0.767499,POR

In [33]:
pvalue_adj_sig = filtered_df_komodo_pic[filtered_df_komodo_pic[f'{sample_type}_pvals_adj'] < 0.05]
komodo_pic_logfc_up = pvalue_adj_sig[pvalue_adj_sig[f'{sample_type}_logfoldchanges'] >= 0]
komodo_pic_logfc_up

,pic_logfoldchanges,pic_pvals,pic_pvals_adj,pic_pts,UNST_pts,1to1_bat_dragon
pic_names,,,,,,
TNIP1,2.522758,1.101900e-208,6.894900e-205,0.780783,0.368086,TNIP1
TNF,3.223141,7.287700e-164,2.736100e-160,0.681243,0.215859,TNF
RNF213,2.893878,4.006000e-162,1.253300e-158,0.677215,0.285365,RNF213
STK17A,2.435132,7.546700e-151,1.574100e-147,0.678941,0.255507,STK17A
UNC13D,1.741788,1.349100e-127,2.110400e-124,0.795742,0.441508,UNC13D
...,...,...,...,...,...,...
CAB39,0.431251,5.579221e-03,4.910133e-02,0.195627,0.144885,CAB39
NIN,0.187616,5.589731e-03,4.917078e-02,0.386076,0.325991,NIN
UBE2H,0.159531,5.595636e-03,4.919966e-02,0.403913,0.346549,UBE2H
YBX1,0.056697,8.690490e-05,1.148050e-03,0.971231,0.940284,YBX1
TKT,0.008712,5.561580e-05,7.642900e-04,0.970081,0.941263,TKT

In [34]:
komodo_pic_logfc_up.to_csv(f'../../data/single_cell/animals/{animal}/{sample_type}/{animal}_{sample_type}_logfc_up_DE.csv')
komodo_pic_logfc_up

,pic_logfoldchanges,pic_pvals,pic_pvals_adj,pic_pts,UNST_pts,1to1_bat_dragon
pic_names,,,,,,
TNIP1,2.522758,1.101900e-208,6.894900e-205,0.780783,0.368086,TNIP1
TNF,3.223141,7.287700e-164,2.736100e-160,0.681243,0.215859,TNF
RNF213,2.893878,4.006000e-162,1.253300e-158,0.677215,0.285365,RNF213
STK17A,2.435132,7.546700e-151,1.574100e-147,0.678941,0.255507,STK17A
UNC13D,1.741788,1.349100e-127,2.110400e-124,0.795742,0.441508,UNC13D
...,...,...,...,...,...,...
CAB39,0.431251,5.579221e-03,4.910133e-02,0.195627,0.144885,CAB39
NIN,0.187616,5.589731e-03,4.917078e-02,0.386076,0.325991,NIN
UBE2H,0.159531,5.595636e-03,4.919966e-02,0.403913,0.346549,UBE2H
YBX1,0.056697,8.690490e-05,1.148050e-03,0.971231,0.940284,YBX1
TKT,0.008712,5.561580e-05,7.642900e-04,0.970081,0.941263,TKT