# Single Cell analysis bat dragon

In [1]:
from itertools import product
from pathlib import Path

import pandas as pd
import numpy as np
import os

In [2]:
# Trying things on the bat_dragon_DE file from the drive

animal_b = 'bat'
animal_k = 'komodo'

sample_type = 'lps'
# sample_type = 'pic'

# bat DF

df_bat_lps = pd.read_csv(f'../../data/single_cell/animals/{animal_b}/{sample_type}/{animal_b}_{sample_type}.csv', index_col=0)
df_bat_lps = df_bat_lps.sort_index()

df_bat_lps

,lps_logfoldchanges,lps_pvals,lps_pvals_adj,lps_pts,UNST_pts,1to1_bat_dragon
lps_names,,,,,,
A1BG,-16.432978,0.992822,1.00000,0.000000,0.000054,no
A1CF,0.562230,0.985360,1.00000,0.000219,0.000108,A1CF
A2M_LOC107501662,-0.359043,0.972370,1.00000,0.000821,0.001030,no
A3GALT2,-0.238440,0.976336,1.00000,0.001698,0.001518,no
A4GALT,-0.239287,0.929291,1.00000,0.007886,0.008405,A4GALT
...,...,...,...,...,...,...
ZYG11A,-2.327192,0.892936,1.00000,0.000219,0.001030,no
ZYG11B,-0.129760,0.789010,1.00000,0.029025,0.030582,no
ZYX,0.129112,0.002529,0.03491,0.244250,0.225572,ZYX
ZZEF1,-0.099973,0.161601,1.00000,0.155257,0.163160,no
ZZZ3,-0.134738,0.175835,1.00000,0.121139,0.128728,ZZZ3

In [3]:
# komodo DF

df_komodo_lps = pd.read_csv(f'../../data/single_cell/animals/{animal_k}/{sample_type}/{animal_k}_{sample_type}.csv', index_col=0)
df_komodo_lps = df_komodo_lps.sort_index()

df_komodo_lps

,lps_logfoldchanges,lps_pvals,lps_pvals_adj,lps_pts,UNST_pts,1to1_bat_dragon
lps_names,,,,,,
26-29-P,-0.015763,0.909815,1.000000,0.792287,0.816936,no
A1CF,0.000000,1.000000,1.000000,0.000000,0.000000,A1CF
A2M_1,-20.112549,0.958082,1.000000,0.000000,0.000979,no
A2M_2,-0.072731,0.945478,1.000000,0.010468,0.011747,no
A2M_3,0.000000,1.000000,1.000000,0.000000,0.000000,no
...,...,...,...,...,...,...
ZXDC,-0.249762,0.407381,1.000000,0.042975,0.058737,ZXDC
ZYG11B_1,-0.104634,0.703775,1.000000,0.047934,0.055311,no
ZYG11B_2,0.598826,0.013411,0.107079,0.192837,0.152227,no
ZYX,-0.193039,0.010989,0.089964,0.202755,0.255507,ZYX
ZZZ3,0.338754,0.537142,1.000000,0.135537,0.126774,ZZZ3

In [4]:
df_combined = df_bat_lps.merge(df_komodo_lps, left_index=True, right_index=True, how='outer')

df_combined

,lps_logfoldchanges_x,lps_pvals_x,lps_pvals_adj_x,lps_pts_x,UNST_pts_x,1to1_bat_dragon_x,lps_logfoldchanges_y,lps_pvals_y,lps_pvals_adj_y,lps_pts_y,UNST_pts_y,1to1_bat_dragon_y
lps_names,,,,,,,,,,,,
26-29-P,NaN,NaN,NaN,NaN,NaN,NaN,-0.015763,0.909815,1.000000,0.792287,0.816936,no
A1BG,-16.432978,0.992822,1.00000,0.000000,0.000054,no,NaN,NaN,NaN,NaN,NaN,NaN
A1CF,0.562230,0.985360,1.00000,0.000219,0.000108,A1CF,0.000000,1.000000,1.000000,0.000000,0.000000,A1CF
A2M_1,NaN,NaN,NaN,NaN,NaN,NaN,-20.112549,0.958082,1.000000,0.000000,0.000979,no
A2M_2,NaN,NaN,NaN,NaN,NaN,NaN,-0.072731,0.945478,1.000000,0.010468,0.011747,no
...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11B_1,NaN,NaN,NaN,NaN,NaN,NaN,-0.104634,0.703775,1.000000,0.047934,0.055311,no
ZYG11B_2,NaN,NaN,NaN,NaN,NaN,NaN,0.598826,0.013411,0.107079,0.192837,0.152227,no
ZYX,0.129112,0.002529,0.03491,0.244250,0.225572,ZYX,-0.193039,0.010989,0.089964,0.202755,0.255507,ZYX
ZZEF1,-0.099973,0.161601,1.00000,0.155257,0.163160,no,NaN,NaN,NaN,NaN,NaN,NaN
ZZZ3,-0.134738,0.175835,1.00000,0.121139,0.128728,ZZZ3,0.338754,0.537142,1.000000,0.135537,0.126774,ZZZ3

In [5]:
# filtering by taking out the rows that says 'no' in the column 1to1_bat_dragon_x (x presents the bat's df)

filtered_df_combined_x = df_combined[df_combined['1to1_bat_dragon_x'] != 'no']

filtered_df_combined_x

,lps_logfoldchanges_x,lps_pvals_x,lps_pvals_adj_x,lps_pts_x,UNST_pts_x,1to1_bat_dragon_x,lps_logfoldchanges_y,lps_pvals_y,lps_pvals_adj_y,lps_pts_y,UNST_pts_y,1to1_bat_dragon_y
lps_names,,,,,,,,,,,,
26-29-P,NaN,NaN,NaN,NaN,NaN,NaN,-0.015763,0.909815,1.000000,0.792287,0.816936,no
A1CF,0.562230,0.985360,1.000000,0.000219,0.000108,A1CF,0.000000,1.000000,1.000000,0.000000,0.000000,A1CF
A2M_1,NaN,NaN,NaN,NaN,NaN,NaN,-20.112549,0.958082,1.000000,0.000000,0.000979,no
A2M_2,NaN,NaN,NaN,NaN,NaN,NaN,-0.072731,0.945478,1.000000,0.010468,0.011747,no
A2M_3,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,0.000000,0.000000,no
...,...,...,...,...,...,...,...,...,...,...,...,...
ZXDC,-0.171241,0.146909,0.995651,0.084611,0.093157,ZXDC,-0.249762,0.407381,1.000000,0.042975,0.058737,ZXDC
ZYG11B_1,NaN,NaN,NaN,NaN,NaN,NaN,-0.104634,0.703775,1.000000,0.047934,0.055311,no
ZYG11B_2,NaN,NaN,NaN,NaN,NaN,NaN,0.598826,0.013411,0.107079,0.192837,0.152227,no
ZYX,0.129112,0.002529,0.034910,0.244250,0.225572,ZYX,-0.193039,0.010989,0.089964,0.202755,0.255507,ZYX
ZZZ3,-0.134738,0.175835,1.000000,0.121139,0.128728,ZZZ3,0.338754,0.537142,1.000000,0.135537,0.126774,ZZZ3

In [6]:
pvalue_adj_sig = filtered_df_combined_x[filtered_df_combined_x[f'{sample_type}_pvals_adj_x'] < 0.05]
combined_lps_logfc_up = pvalue_adj_sig[pvalue_adj_sig[f'{sample_type}_logfoldchanges_x'] >= 0]
combined_lps_logfc_up.sort_values(by=['lps_logfoldchanges_x'], ascending=False, inplace=True)

combined_lps_logfc_up

C:\Users\TzachiHNB2\AppData\Local\Temp\ipykernel_6844\4011180955.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_lps_logfc_up.sort_values(by=['lps_logfoldchanges_x'], ascending=False, inplace=True)

,lps_logfoldchanges_x,lps_pvals_x,lps_pvals_adj_x,lps_pts_x,UNST_pts_x,1to1_bat_dragon_x,lps_logfoldchanges_y,lps_pvals_y,lps_pvals_adj_y,lps_pts_y,UNST_pts_y,1to1_bat_dragon_y
lps_names,,,,,,,,,,,,
PTGES,3.373746,2.857180e-16,1.495100e-14,0.056791,0.007646,PTGES,2.746322,5.832090e-15,2.778680e-13,0.182369,0.039158,PTGES
EDN1,2.413236,6.416960e-04,1.029940e-02,0.026670,0.006127,EDN1,2.425764,8.798341e-01,1.000000e+00,0.003306,0.000489,EDN1
INHBA,2.350872,6.161810e-13,2.689710e-11,0.058050,0.014912,INHBA,3.082251,5.669640e-30,7.002000e-28,0.252893,0.044053,INHBA
ISG15,2.229802,0.000000e+00,0.000000e+00,0.940088,0.727470,ISG15,2.336883,5.272624e-02,3.387327e-01,0.046281,0.010279,ISG15
TNFAIP6,2.199447,1.278890e-15,6.466870e-14,0.066758,0.018870,TNFAIP6,1.045027,7.846681e-01,1.000000e+00,0.010468,0.005384,TNFAIP6
...,...,...,...,...,...,...,...,...,...,...,...,...
GABARAPL2,0.080026,5.648090e-04,9.128455e-03,0.671084,0.652912,GABARAPL2,0.069186,9.277663e-01,1.000000e+00,0.307989,0.317670,GABARAPL2
NDFIP1,0.079292,3.749302e-03,4.917420e-02,0.425630,0.403590,NDFIP1,-0.487953,1.332430e-20,9.694750e-19,0.687052,0.776799,NDFIP1
GRB2,0.078768,3.536067e-03,4.671341e-02,0.472015,0.449301,GRB2,-0.067327,2.461419e-01,1.000000e+00,0.781818,0.796867,GRB2
SRRM1,0.075248,3.657050e-03,4.815440e-02,0.550876,0.528793,SRRM1,0.134113,3.330271e-02,2.298377e-01,0.680992,0.680372,SRRM1
MBNL1,0.065094,3.197120e-05,6.547050e-04,0.842881,0.831146,MBNL1,-0.593499,3.208800e-20,2.264500e-18,0.596694,0.725893,MBNL1

In [7]:
combined_lps_logfc_up.to_csv(f'../../data/single_cell/animals/{animal_b}/{sample_type}/{animal_b}_{sample_type}_logfc_up_combined.csv')

combined_lps_logfc_up

,lps_logfoldchanges_x,lps_pvals_x,lps_pvals_adj_x,lps_pts_x,UNST_pts_x,1to1_bat_dragon_x,lps_logfoldchanges_y,lps_pvals_y,lps_pvals_adj_y,lps_pts_y,UNST_pts_y,1to1_bat_dragon_y
lps_names,,,,,,,,,,,,
PTGES,3.373746,2.857180e-16,1.495100e-14,0.056791,0.007646,PTGES,2.746322,5.832090e-15,2.778680e-13,0.182369,0.039158,PTGES
EDN1,2.413236,6.416960e-04,1.029940e-02,0.026670,0.006127,EDN1,2.425764,8.798341e-01,1.000000e+00,0.003306,0.000489,EDN1
INHBA,2.350872,6.161810e-13,2.689710e-11,0.058050,0.014912,INHBA,3.082251,5.669640e-30,7.002000e-28,0.252893,0.044053,INHBA
ISG15,2.229802,0.000000e+00,0.000000e+00,0.940088,0.727470,ISG15,2.336883,5.272624e-02,3.387327e-01,0.046281,0.010279,ISG15
TNFAIP6,2.199447,1.278890e-15,6.466870e-14,0.066758,0.018870,TNFAIP6,1.045027,7.846681e-01,1.000000e+00,0.010468,0.005384,TNFAIP6
...,...,...,...,...,...,...,...,...,...,...,...,...
GABARAPL2,0.080026,5.648090e-04,9.128455e-03,0.671084,0.652912,GABARAPL2,0.069186,9.277663e-01,1.000000e+00,0.307989,0.317670,GABARAPL2
NDFIP1,0.079292,3.749302e-03,4.917420e-02,0.425630,0.403590,NDFIP1,-0.487953,1.332430e-20,9.694750e-19,0.687052,0.776799,NDFIP1
GRB2,0.078768,3.536067e-03,4.671341e-02,0.472015,0.449301,GRB2,-0.067327,2.461419e-01,1.000000e+00,0.781818,0.796867,GRB2
SRRM1,0.075248,3.657050e-03,4.815440e-02,0.550876,0.528793,SRRM1,0.134113,3.330271e-02,2.298377e-01,0.680992,0.680372,SRRM1
MBNL1,0.065094,3.197120e-05,6.547050e-04,0.842881,0.831146,MBNL1,-0.593499,3.208800e-20,2.264500e-18,0.596694,0.725893,MBNL1

In [ ]:
# filtered_df_combined_y = df_combined[df_combined['1to1_bat_dragon_y'] != 'no']

# filtered_df_combined_y

In [ ]:
# Trying things on the bat_dragon_DE file from the drive

# animals = ['bat', 'komodo']
# sample_types = ['lps', 'pic']

# for animal, sample_type in product(animals, sample_types):
        # path = (f'/Code/data/single_cell/animals/{animal}/{sample_type}/{animal}_{sample_type}.csv')
        # print(path)

        # if os.path.exists(path):
            # df = pd.read_csv(path)
        # df

#### Filtering out rows that are not 1 to 1 ortholgs (has 'no' in the 1to1_bat_dragon column)

In [ ]:
# Filter out the row where 'no' appears

# filtered_df_komodo_pic = df_komodo_pic[df_komodo_pic['1to1_bat_dragon'] != 'no']
# filtered_df_komodo_pic

In [ ]:
# pvalue_adj_sig = filtered_df_komodo_pic[filtered_df_komodo_pic[f'{sample_type}_pvals_adj'] < 0.05]
# komodo_pic_logfc_up = pvalue_adj_sig[pvalue_adj_sig[f'{sample_type}_logfoldchanges'] >= 0]
# komodo_pic_logfc_up

In [ ]:
# komodo_pic_logfc_up.to_csv(f'../../data/single_cell/animals/{animal}/{sample_type}/{animal}_{sample_type}_logfc_up_DE.csv')
# komodo_pic_logfc_up

In [ ]:
# combining two DF - bat and komodo

# df_combined = df_komodo_pic.merge(df_animals, left_index=True, right_index=True, how='inner')

# df_combined